[workspace]
resolver = "2"
members = ["crates/sframe-ptt", "crates/audio-engine", "crates/android-jni", "crates/apple-ffi"]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-only"
version = "0.0.1"

[workspace.dependencies]
aes-gcm = "0.11"
hkdf = "0.13"
opus = "0.4"
jni = "0.22"
sha2 = "0.11"
thiserror = "2"
