{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ptt.fullname" . }}
  labels:
    {{- include "ptt.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.rateLimit.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-%s-rate-limit@kubernetescrd" .Release.Namespace (include "ptt.fullname" .) | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts: [{{ .Values.ingress.host | quote }}]
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: {{ include "ptt.fullname" . }}-admin-web
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ptt.fullname" . }}-control
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ptt.fullname" . }}-grpc
  labels:
    {{- include "ptt.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.rateLimit.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-%s-rate-limit@kubernetescrd" .Release.Namespace (include "ptt.fullname" .) | quote }}
    {{- end }}
    {{- with .Values.ingress.grpcAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts: [{{ required "ingress.grpcHost is required" .Values.ingress.grpcHost | quote }}]
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ required "ingress.grpcHost is required" .Values.ingress.grpcHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ptt.fullname" . }}-control-grpc
                port:
                  name: grpc
{{- end }}
