apiVersion: v1
kind: Service
metadata:
  name: {{ include "ptt.fullname" . }}-redis
  labels:
    {{- include "ptt.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "ptt.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ptt.fullname" . }}-redis
  labels:
    {{- include "ptt.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ptt.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ptt.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ptt.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: redis
    spec:
      serviceAccountName: {{ include "ptt.serviceAccountName" . }}
      securityContext:
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          args:
            - redis-server
            - --appendonly
            - "yes"
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ptt.fullname" . }}
                  key: redis-password
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.redis.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.redis.storage }}
