name: export-ios-simulator-libsignal

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export:
    runs-on: [self-hosted, macOS, ARM64, ptt-build]
    steps:
      - uses: actions/checkout@v4
      - name: Build simulator libsignal
        run: ./scripts/build-libsignal-ios-sim.sh
      - name: Upload temporary draft-release asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh release upload ci-libsignal-temp
          /Users/golanbenoni/src/libsignal/target/aarch64-apple-ios-sim/debug/libsignal_ffi.a
          --clobber
